Update main_ghiblify.yml

diff --git a/.github/workflows/main_ghiblify.yml b/.github/workflows/main_ghiblify.yml
--- a/.github/workflows/main_ghiblify.yml
+++ b/.github/workflows/main_ghiblify.yml
@@ -23,14 +23,22 @@ jobs:
         with:
           node-version: '20.x'
 
-      - name: npm install, build, and test
-        run: |
-          npm install
-          npm run build --if-present
-          npm run test --if-present
+      - name: Install dependencies
+        run: npm install
 
-      - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+      - name: Build React App
+        run: npm run build
+      
+      - name: Verify Build Folder
+        run: |
+          if [ ! -d "dist" ]; then
+            echo "Build folder not found! Build failed."
+            exit 1
+          fi
+
+      - name: Zip build folder for deployment
+        run: zip release.zip dist -r
+
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
